config/routes.rb
Rails.application.routes.draw do

    # get "/lessons/new"
    # get 'lessons/new'

    root :to => "pages#home"
    resources :users

    get "/login" => 'session#new'
    post "login" => 'session#create'
    delete '/login'=> 'session#destroy'

    resources :bookings
    resources :lessons
    get "/admin" =>  'admin#home'
    get '/bookings' => 'bookings#home'
    get '/lessons' => 'lessons#home'
    get '/users' => 'users#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user, :optional =>true
  belongs_to :lesson, :optional => true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user, :optional => true
  has_many :bookings
  belongs_to :location, :optional => true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :lessons
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :presence => true, :uniqueness => true
  has_secure_password
  has_many :lessons
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :fetch_user

   private
    def fetch_user
     @current_user = User.find_by :id => session[:user_id] if
     session[:user_id].present?
     session[:user_id]=nil unless @current_user.present?

    end

   def check_for_login
     redirect_to login_path unless @current_user.present?
   end

   def check_for_admin
     redirect_to login_path unless (@current_user.present? &&
     @current_user.admin?)
   end

   def check_for_instructor
       redirect_to login_path unless (@current_user.present? &&
       @current_user.instructor?)
   end



end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :check_for_login, :except => [:new]

  def index
    @bookings=Booking.all
  end
  def home
      @bookings = @current_user.bookings
  end
  def show
    @booking = Booking.find params[:id]
    @client = OpenStreetMap::Client.new
      #create an object
      @search = @client.search(q: "#{@booking.lesson.suburb}, #{@booking.lesson.postcode}",format: 'json', addressdetails: '1', accept_language: 'en')
      #extract value from JSON response
      if @search.any?
        @bounding_box = @search[0]["boundingbox"]
        @south_latitude = @bounding_box[0]
        @north_latitude = @bounding_box[1]
        @west_longitude = @bounding_box[2]
        @east_longitude = @bounding_box[3]

      #arrange longitude and latitude in bounding box as, bbox = min Longitude , min Latitude , max Longitude , max Latitude
      @bbox = @west_longitude + '%2C' + @south_latitude + '%2C' + @east_longitude + '%2C' + @north_latitude
      #extract value longitude and latitude values for marker
      @longitude = @search[0]["lon"]
      @latitude = @search[0]["lat"]
      @marker = @longitude + '%2C' + @latitude
    end
  end

  def new
    @booking = Booking.new
  end



  def create
    booking = Booking.create booking_params
    @current_user.bookings << booking
    redirect_to bookings_path

  end

  def edit

  @booking = Booking.find params[:id]
  end

  def update
    booking= Booking.find params[:id]
    booking.update booking_params
    redirect_to bookings_path
  end

  def destroy
    booking=Booking.find params[:id]
    booking.destroy
    redirect_to bookings_path
  end





  private
  def booking_params
    params.require(:booking).permit(:title,:user_id,:date,:description,:location,:contact, :image,:time,:date, :lesson_id)
  end








end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :check_for_login, :except => [:new]
  def index
    @lessons=Lesson.all
  end
  # def home
  #     @lessons = @current_user.lessons
  # end
  def show
  @lesson = Lesson.find params[:id]
  # Using open street map API
  @client = OpenStreetMap::Client.new
    #create an object
    @search = @client.search(q: "#{@lesson.suburb}, #{@lesson.postcode}",format: 'json', addressdetails: '1', accept_language: 'en')
    #extract value from JSON response
    if @search.any?
      @bounding_box = @search[0]["boundingbox"]
      @south_latitude = @bounding_box[0]
      @north_latitude = @bounding_box[1]
      @west_longitude = @bounding_box[2]
      @east_longitude = @bounding_box[3]

    #arrange longitude and latitude in bounding box as, bbox = min Longitude , min Latitude , max Longitude , max Latitude
    @bbox = @west_longitude + '%2C' + @south_latitude + '%2C' + @east_longitude + '%2C' + @north_latitude
    #extract value longitude and latitude values for marker
    @longitude = @search[0]["lon"]
    @latitude = @search[0]["lat"]
    @marker = @longitude + '%2C' + @latitude
  end
end

  def new
    @lesson = Lesson.new
  end


  def create
    lesson = Lesson.create lesson_params
    @current_user.lessons << lesson
    redirect_to lessons_path

  end

  def edit
  @lesson = Lesson.find params[:id]
  end

  def update
    lesson= Lesson.find params[:id]
    lesson.update lesson_params
    redirect_to lessons_path
  end

  def destroy
    lesson=Lesson.find params[:id]
    lesson.destroy
    redirect_to lessons_path
  end

  private
  def lesson_params
    params.require(:lesson).permit(:title,:user_id,:booking_id,:date,:description,:location,:contact, :image, :suburb, :postcode, :time)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
before_action :check_for_login
#...
  def home
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def home
  end
 
  def create
    user=User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] =user.id
      if user.admin?
        redirect_to users_path
      else
        redirect_to user
      end
    else
      redirect_to login_path
    end
  end
    def destroy
      session[:user_id]=nil
      redirect_to login_path
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]

  def home
  end
  def index
     @users = User.all
  end

  def show
     @user=User.find params[:id]
  end


  def new
     @user =User.new
  end

  def create
     @user = User.new user_params
    if @user.save
       session[:user_id]= @user.id
       redirect_to root_path
    else
       render :new
    end
  end


  def edit
   @user = User.find params[:id]

  end

  def update
     user= User.find params[:id]
     user.update user_params

     redirect_to edit_user_path(user)
  end
  def destroy
    lesson=User.find params[:id]
    user.destroy
    redirect_to users_path
  end
   private
  def user_params
     params.require(:user).permit(:email, :password, :password_confirmation, :instructor,:name,:address,:phonenumber,:description,
     :about,:image,:dob,:location)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/_form.hmtl.erb
<%= form_for @booking do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/bookings/_form.html.erb
<div class="div-color">
  <h1>Edit booking</h1>
  <%= form_for @booking do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title ,:class => 'form-control'%>
  </div>
    <%= f.submit "Edit booking", :class => "btn btn-info" %>
  <% end %>
</div>

app/views/bookings/edit.html.erb
<%= render :partial => "form" %>

app/views/bookings/home.html.erb
  <div class="div-color">
    <h1>Namaste, <%= @current_user.email %>!</h1>
    <h2> You have got <%= pluralize(@current_user.bookings.count, 'booking')  %> available.</h2>
    <% @bookings.each do |booking| %>
    <p>
    <%= booking.title %>
    </p>
  <% end %>
  </div>

app/views/bookings/index.html.erb
<div class="div-color">
  <h1>Namaste, <%= @current_user.name %>!</h1>
  <h2> You have got <%= pluralize(@current_user.bookings.count, 'booking')  %> available.</h2>

  <% @current_user.bookings.each do |booking| %>
  <p><%= booking.lesson.title %></p>
  <div class=“controls”>
    <%= link_to "View booking", booking%>
    <%= link_to "Edit booking", edit_booking_path(booking) %>
    <%= link_to "Delete booking", booking, :method => 'delete', :data => { :confirm => "Are you sure?"} %>

</div>
<% end %>
</div>

app/views/bookings/new.html.erb
<div class="div-color">
  <h1>New booking</h1>
  <%= form_for @booking do |f| %>
  <div class="custom-file">
  <%= f.label "Class"%>
  <%= f.select :lesson_id, Lesson.pluck(:title, :id), :include_blank => true, :class => 'custom-select custom-select-lg'%>
  </div>
  <%= f.submit "Make a new booking" , :class => "btn btn-info"%>
  <% end %>

</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

app/views/bookings/show.html.erb
  <div class="div-color">
    <h1><%= @booking.lesson.title %></h1>
    <%= image_tag @booking.lesson.image, :class => 'thumb' if @booking.lesson.image.present? %>

    <ul>
      <li>Date: <%= @booking.lesson.date.strftime '%A, %B %e, %Y' %></li>
      <li>Time: <%= @booking.lesson.time.strftime '%H:%M %p' %></li>
      <li>Description: <%= @booking.lesson.description%></li>
      <li>Suburb: <%= @booking.lesson.suburb %>, <%= @booking.lesson.postcode %></li>
      <li>Your instructor: <%= @booking.lesson.contact %></li>
    </ul>
    <div >
      <h3>Beach location</h3>
            <!-- used iframe to display openstreetmap -->
        <iframe width="425" height="350" frameborder="0" scrolling="no"
          marginheight="0" marginwidth="0"
          src="https://www.openstreetmap.org/export/embed.html?bbox=<%= @bbox %>&amp;layer=mapnik&amp;marker=<%= @marker%>"
          style="border: 1px solid black">
        </iframe>
  </div>
   </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yoga4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no">
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light justify-content ">
         <a class="navbar-brand" href="#"></a>
         <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
         </button> -->
         <div  class="navbar-expand"  id="navbarSupportedContent">
           <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href=<%=root_path %>> Home <span class="sr-only">(current)</span></a>
            </li>
            <% if @current_user.present? %>
            <% if @current_user.admin? %>
            <li class="nav-item">
              <a class="nav-link" href=<%= users_path %>>All users</a>
            </li>
            <%end %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Your stuff
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href=<%= new_booking_path %>>New booking</a>
                <% if @current_user.present? && @current_user.instructor? %>
                <%= link_to "New class", new_lesson_path, :class => "dropdown-item" %>
                <% end %>
                <a class="dropdown-item" href=<%=  edit_user_path(@current_user) %>>Your profile</a>
                <%= link_to "Log out #{ @current_user.email}", login_path, :method => 'delete', :class =>"dropdown-item" %>
              </div>
            </li>
            <% else %>
            <li class="nav-item">
              <a class="nav-link" href=<%= new_user_path %>>Sign Up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href=<%= login_path %>>Sign in</a>
            </li>
            <% end %>

          </ul>

        </div>
      </nav>
</div>
  <div >
    <%= yield %>
  </div>

    <footer>
      <nav class="navbar navbar-expand-lg" id='footer'>
        <a class="navbar-brand" href="https://www.facebook.com/groups/1796384610660298" target='_blank'>

          <div class="text-center">
            <img src="https://i.imgur.com/fFIzW9y.png" class="rounded" alt="Facebook" width='35' height='35'>
          </div>
        </a>
        <a class="navbar-brand" href='https://www.instagram.com/aleckuzman/' target='_blank'>
          <div class="text-center">
            <img src="https://i.imgur.com/x1ZL1Ab.png" class="rounded" alt="Instagram" width='35' height='35'>
          </div>
        </a>
        <a class="navbar-brand" href='https://www.youtube.com/watch?v=PkX_cPuS92c&ab_channel=IyengarYogaMaidaVale/UC__IHhHuwMtGl5zfjD-Tu4g' target='_blank'>
          <div class="text-center">
            <img src="https://i.imgur.com/ahMyH95.png" class="rounded" alt="Youtube" width='35' height='35'>
          </div>
        </a>
    </nav>
  </footer>


  </body>

</html>

app/views/lessons/_form.html.erb
<div class="div-color">
  <%= form_for @lesson do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title,:class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :date %>
    <%= f.date_field :date,:class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :time %>
    <%= f.time_field :time,:class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :suburb %>
    <%= f.text_field :suburb,:class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :postcode %>
    <%= f.number_field :postcode,:class => 'form-control'%>
  </div>
    <%= f.submit "Edit class", :class => "btn btn-info" %>
  <% end %>
</div>

app/views/lessons/edit.html.erb
<h1>Edit class</h1>

<%= render :partial => 'form' %>

app/views/lessons/home.html.erb
<div class="div-color">
<h1>Hi <%= @current_user.email %></h1>
<h2> You have got <%= pluralize(@current_user.lessons.count, 'class')  %> available.</h2>
<% @lessons.each do |lesson| %>
<p><%= lesson.title %></p>
<% end %>
</div>

app/views/lessons/index.html.erb
<div class="div-color">
<h1>All classes,</h1>

<h1>Namaste, <%= @current_user.email %>!</h1>

<h2> You have got <%= pluralize(@current_user.lessons.count, 'class')  %> available.</h2>

<% @current_user.lessons.each do |lesson| %>
<p><%= lesson.title %></p>

<div class=“controls”>
  <%= link_to "View class", lesson %>
  <%= link_to "Edit class", edit_lesson_path(lesson) %>
  <%= link_to "Delete class", lesson, :method => 'delete', :data => { :confirm => "Are you sure?"} %> <br><br>
</div>
<% end %>
</div>

app/views/lessons/new.html.erb
<div class="div-color">
  <% if @current_user.present?%>
  <h1>New class</h1>


  <%= form_for @lesson do |f| %>
  <div class="form-group">
  <%= f.label :image %>
  <%= f.text_field :image,:class => 'form-control' %>
  </div>
  <div class="form-group">
  <%= f.label "Class" %>
  <%= f.text_field :title,:class => 'form-control' %>
  </div>
  <div class="form-group">
  <%= f.label :date %>
  <%= f.date_field :date,:class => 'form-control' %>
  </div>
  <div class="form-group">
  <%= f.label :time %>
  <%= f.time_field :time,:class => 'form-control' %>
  </div>
  <div class="form-group">
  <%= f.label :description %>
  <%= f.text_field :description ,:class => 'form-control'%>
  </div>
  <div class="form-group">
  <%= f.label :suburb %>
  <%= f.text_field :suburb,:class => 'form-control' %>
  </div>
  <div class="form-group">
  <%= f.label :postcode %>
  <%= f.number_field :postcode,:class => 'form-control'%>
  </div>
  <div class="form-group">
  <%= f.label "Your instructor" %>
  <%= f.text_field :contact,:class => 'form-control' %>
  </div>


  <%= f.submit "Create a new class", :class => "btn btn-info" %>
  <% end %>
  <% end %>
</div>

app/views/lessons/show.html.erb
<div class="div-color">
  <h1><%= @lesson.title %></h1>

  <%= image_tag @lesson.image, :class => 'thumb' if @lesson.image.present? %>
  <ul>
    <li>Description: <%= @lesson.description%></li>
    <li>Time: <%= @lesson.date.strftime '%A, %B %e, %Y' %></li>
    <li>Date: <%= @lesson.time.strftime '%H:%M %p'%></li>
    <li>Suburb: <%= @lesson.suburb%></li>
    <li>Postcode:<%= @lesson.postcode%></li>
    <li>instructor<%= @lesson.contact%></li>
  </ul>
  <div >
    <h3>Location</h3>
    <!-- used iframe to display openstreetmap -->
    <iframe width="425" height="350" frameborder="0" scrolling="no"
      marginheight="0" marginwidth="0"
      src="https://www.openstreetmap.org/export/embed.html?bbox=<%= @bbox %>&amp;layer=mapnik&amp;marker=<%= @marker%>"
      style="border: 1px solid black">
    </iframe>
  </div>
  </div>

app/views/pages/home.html.erb
<% if @current_user.present?%>
<div class="jumbotron container">
  <h1 class="display-4">Namaste <%= link_to @current_user.name, user_path(@current_user.id) %>!</h1>
  <p class="lead">"Inhale the future, exhale the past."</p>
  <hr class="my-4">
  <p>You have got <%=link_to pluralize(@current_user.bookings.count,    'booking'), bookings_path  %>
    <% if @current_user.instructor? %>
  and
   <%= link_to pluralize(@current_user.lessons.count, 'class'),lessons_path %> available
  <% end %></p>
  <%end %>

</div>

app/views/session/new.html.erb
<div class="div-color">
  <h1>Log in</h1>
  <%= form_tag login_path do %>
    <div class="form-group">
      <%= label_tag :email %>
      <%= email_field_tag :email,nil, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :password %>
      <%= password_field_tag :password,nil, :class => 'form-control'%>
    </div>

      <%= submit_tag "Sign In", :class => 'btn btn-info btn-lg' %>
   <% end %>
</div>
<br><br><br><br><br><br><br><br><br><br><br>

app/views/users/_form.html.erb
<div class="div-color">
  <h1>Edit your profile</h1>
  <%= form_for @user do |f| %>

  <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name,:class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= label_tag :email %>
    <%= email_field_tag :email,nil,:class => 'form-control' %>
  </div>
  <div class="form-group">
  <%= f.label :address %>
  <%= f.text_field :address,:class => 'form-control' %>
  </div>
  <div class="form-group">
  <%= f.label "Phone number:" %>
  <%= f.number_field :phonenumber, :class => 'form-control' %>
  </div>
  <div class="form-group">
  <%= f.label :about %>
  <%= f.text_field :about,:class => 'form-control' %>
  </div>
  <div class="form-group">
  <%= f.label :image %>
  <%= f.text_field :image, :class => 'form-control' %>
  </div>
  <div class="form-group">
  <%= f.label :location %>
  <%= f.text_field :location,:class => 'form-control' %>
  </div>
  <div class="form-group">
  <%= f.label "Date of Birth" %>
  <%= f.date_field :dob,:class => 'form-control' %>
  </div>

  <%= f.submit "Edit profile", :class => 'btn btn-info btn-lg'%>
<% end %>

</div>

app/views/users/index.html.erb
<div class="div-color">

<h2>You have <%= User.count %> users </h2><br>

<% @users.each do |user| %>


<%= image_tag user.image, :class => 'thumb' if user.image.present? %>
<ul>
  <li>Name: <%= user.name %></li>
  <% if user.dob.present? %>
  <li>Date of birth: <%= user.dob.strftime '%A, %B %e, %Y' %></li>
  <% end %>
  <li>Location: <%= user.location %></li>
  <li>Email: <%= user.email %></li>
  <li><% if @current_user.admin? %>
    <%= link_to "Remove User", @user, :method => 'delete', :data => {:confirm => "Are you sure, you want to remove user permanently?"}, :class => "remove" %>
  <% end %>
</li>
</ul>
<% end %>
</div>

app/views/users/new.html.erb
<div class="div-color">
    <h1>Sign up!</h1>
    <% if @user.errors.any? %>
    <ol>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ol>
    <% end %>


    <%= form_for @user do |f| %>

    <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, :class => 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :class => 'form-control'%>
    </div>
    <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.label "Are you an instructor?" %>
    <%= f.check_box :instructor%>
    </div>

    <%= f.submit "Sign up", :class => "btn btn-info" %>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="div-color div-margin">
<h1>Hello
<% if @current_user.name.present?%>
  <%= @current_user.name %>!</h1>
<% end %>
  <p>"It's not about being good at something. It's about being good to yourself."</p>

  <img src="https://happier1.imgix.net/img/blog/20150422-Yoga_10.jpg?w=700" class="img-fluid" alt="picture">
</div>